name: entropy_vpn
description: "Windows VPN client for Xray-core and Sing-box."
publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  jovial_svg: ^1.1.29
  path: ^1.9.1
  image_picker: ^1.2.2
  mobile_scanner: ^7.2.0
  file_picker: ^11.0.2
  pasteboard: ^0.5.0
  qr_code_dart_decoder: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - entropylogo.png
    - assets/flags/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Variable.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Variable.ttf
